'use server'
import { revalidatePath } from 'next/cache'
import { redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'
import { isStaffRole } from '@/lib/auth/roles'
async function staff(){const s=await createClient();const{data:c}=await s.auth.getClaims();const uid=c?.claims?.sub as string|undefined;if(!uid)redirect('/login');const{data:p}=await s.from('profiles').select('role').eq('id',uid).maybeSingle();if(!isStaffRole(p?.role))redirect('/admin');return{s,uid,role:p.role}}
export async function initializeIC(f:FormData){const{s}=await staff();const project_id=String(f.get('project_id'));const application_id=f.get('application_id')||null;const{error}=await s.rpc('initialize_investment_committee',{p_project_id:project_id,p_application_id:application_id});if(error)throw new Error(error.message);revalidatePath('/admin/projects/'+project_id+'/ic')}
export async function saveICDecision(f:FormData){const{s,uid,role}=await staff();if(!['admin','executive','cfo','finance'].includes(role))throw new Error('Solo roles autorizados pueden registrar decisión del Investment Committee.');const project_id=String(f.get('project_id'));const decision=String(f.get('decision'));if(['approved','conditional'].includes(decision)&&String(f.get('quorum_confirmed'))!=='yes')throw new Error('Debe confirmarse el quorum antes de aprobar.');const{error}=await s.from('project_ic_decisions').upsert({project_id,decision,decision_date:new Date().toISOString().slice(0,10),proposed_structure:String(f.get('proposed_structure')||''),proposed_ownership:String(f.get('proposed_ownership')||''),proposed_fees:String(f.get('proposed_fees')||''),conditions:String(f.get('conditions')||''),rationale:String(f.get('rationale')||''),dissenting_notes:String(f.get('dissenting_notes')||''),next_steps:String(f.get('next_steps')||''),quorum_confirmed:String(f.get('quorum_confirmed'))==='yes',conflicts_declared:String(f.get('conflicts_declared'))==='yes',approved_by:uid},{onConflict:'project_id'});if(error)throw new Error(error.message);revalidatePath('/admin/projects/'+project_id+'/ic')}
export async function saveMember(f:FormData){const{s}=await staff();const project_id=String(f.get('project_id'));const{error}=await s.from('project_ic_members').upsert({project_id,member_id:String(f.get('member_id')),role:String(f.get('role')||''),attendance:String(f.get('attendance')||'pending'),conflict_note:String(f.get('conflict_note')||''),vote:f.get('vote')||null},{onConflict:'project_id,member_id'});if(error)throw new Error(error.message);revalidatePath('/admin/projects/'+project_id+'/ic')}
