'use server'
import { revalidatePath } from 'next/cache'
import { redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'
import { isStaffRole } from '@/lib/auth/roles'
async function staff(){const s=await createClient();const{data:c}=await s.auth.getClaims();const uid=c?.claims?.sub as string|undefined;if(!uid)redirect('/login');const{data:p}=await s.from('profiles').select('role').eq('id',uid).maybeSingle();if(!isStaffRole(p?.role))redirect('/admin');return{s,uid,role:p.role}}
export async function initializeIC(f:FormData){const{s}=await staff();const project_id=String(f.get('project_id'));const application_id=f.get('application_id')||null;const{error}=await s.rpc('initialize_investment_committee',{p_project_id:project_id,p_application_id:application_id});if(error)throw new Error(error.message);revalidatePath('/admin/projects/'+project_id+'/ic')}
export async function saveICDecision(f:FormData){const{s,uid,role}=await staff();if(!['admin','executive','cfo','finance'].includes(role))throw new Error('Solo roles autorizados pueden registrar decisión del Investment Committee.');const project_id=String(f.get('project_id'));const decision=String(f.get('decision'));const{data:app}=await s.from('funding_applications').select('id').eq('project_id',project_id).order('created_at',{ascending:false}).limit(1).maybeSingle();if(['approved','conditional'].includes(decision)){const{data:memo}=await s.from('project_investment_memos').select('status').eq('application_id',app?.id||'').maybeSingle();if(memo?.status!=='ready_for_committee'&&memo?.status!=='approved'&&memo?.status!=='conditional')throw new Error('El Investment Memo debe estar listo para Comité antes de registrar una aprobación.');const{data:model}=await s.from('project_financial_models').select('status,calculated_irr,calculated_npv,calculated_dscr').eq('project_id',project_id).maybeSingle();if(!model||!['validated','under_review'].includes(model.status))throw new Error('El modelo financiero debe estar validado o en revisión antes de la decisión.');if(model.calculated_irr===null||model.calculated_npv===null)throw new Error('Faltan métricas financieras calculadas. Ejecute el Financial Engine.');}if(['approved','conditional'].includes(decision)){if(String(f.get('quorum_confirmed'))!=='yes')throw new Error('Debe confirmarse el quorum antes de aprobar.');if(String(f.get('conflicts_declared'))!=='yes')throw new Error('Debe declararse el manejo de conflictos antes de aprobar.');}const{error}=await s.from('project_ic_decisions').upsert({project_id,decision,decision_date:new Date().toISOString().slice(0,10),proposed_structure:String(f.get('proposed_structure')||''),proposed_ownership:String(f.get('proposed_ownership')||''),proposed_fees:String(f.get('proposed_fees')||''),conditions:String(f.get('conditions')||''),rationale:String(f.get('rationale')||''),dissenting_notes:String(f.get('dissenting_notes')||''),next_steps:String(f.get('next_steps')||''),quorum_confirmed:String(f.get('quorum_confirmed'))==='yes',conflicts_declared:String(f.get('conflicts_declared'))==='yes',approved_by:uid},{onConflict:'project_id'});if(error)throw new Error(error.message);revalidatePath('/admin/projects/'+project_id+'/ic')}
export async function saveMember(f:FormData){const{s,role}=await staff();if(!['admin','executive','cfo','finance','legal','risk_manager'].includes(role))throw new Error('No autorizado para gestionar miembros del comité.');const project_id=String(f.get('project_id'));const{error}=await s.from('project_ic_members').upsert({project_id,member_id:String(f.get('member_id')),role:String(f.get('role')||''),attendance:String(f.get('attendance')||'pending'),conflict_note:String(f.get('conflict_note')||''),vote:f.get('vote')||null},{onConflict:'project_id,member_id'});if(error)throw new Error(error.message);revalidatePath('/admin/projects/'+project_id+'/ic')}
