'use server'
import { revalidatePath } from 'next/cache'
import { redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'
import { isStaffRole } from '@/lib/auth/roles'
async function staff(roles:string[]=[]){const s=await createClient();const {data:c}=await s.auth.getClaims();const uid=c?.claims?.sub as string|undefined;if(!uid)redirect('/login');const {data:p}=await s.from('profiles').select('role').eq('id',uid).maybeSingle();if(!isStaffRole(p?.role)||(roles.length&&!roles.includes(p.role)))redirect('/admin');return{s,uid}}
const num=(v:FormDataEntryValue|null)=>{const n=Number(v);return v===null||v===''?0:(Number.isFinite(n)?n:0)}
export async function refreshCapitalization(f:FormData){const{s}=await staff();const application_id=String(f.get('application_id'));const{error}=await s.rpc('refresh_financial_close_summary',{p_application_id:application_id});if(error)throw new Error(error.message);revalidatePath('/admin/applications/'+application_id)}
export async function saveCapitalCommitment(f:FormData){const{s,uid}=await staff();const application_id=String(f.get('application_id'));const{data:a}=await s.from('funding_applications').select('id,project_id').eq('id',application_id).maybeSingle();if(!a)throw new Error('Solicitud no encontrada');const{error}=await s.from('project_capital_commitments').insert({application_id,project_id:a.project_id||null,capital_source_id:f.get('capital_source_id')||null,capital_stack_id:f.get('capital_stack_id')||null,commitment_type:String(f.get('commitment_type')||'other'),committed_amount:num(f.get('committed_amount')),funded_amount:num(f.get('funded_amount')),currency:String(f.get('currency')||'USD'),status:String(f.get('status')||'proposed'),commitment_date:f.get('commitment_date')||null,evidence_note:String(f.get('evidence_note')||''),created_by:uid});if(error)throw new Error(error.message);await s.rpc('refresh_financial_close_summary',{p_application_id:application_id});revalidatePath('/admin/applications/'+application_id)}
export async function approveFinancialClose(f:FormData){const{s}=await staff(['admin','finance','cfo','executive']);const application_id=String(f.get('application_id'));const{error}=await s.rpc('approve_financial_close',{p_application_id:application_id});if(error)throw new Error(error.message);revalidatePath('/admin/applications/'+application_id)}
export async function closeFinancialClose(f:FormData){const{s}=await staff(['admin','finance','cfo','executive']);const application_id=String(f.get('application_id'));const{error}=await s.from('financial_close_summaries').update({status:'closed',closed_at:new Date().toISOString()}).eq('application_id',application_id).eq('status','approved');if(error)throw new Error(error.message);revalidatePath('/admin/applications/'+application_id)}

export async function updateExecutionControl(f:FormData){const{s,uid}=await staff(['admin','project_manager','developer','finance','cfo','executive','procurement','accounting','supervisor']);const application_id=String(f.get('application_id'));const payload:any={updated_by:uid,status:String(f.get('status')||'mobilization'),approved_budget:f.get('approved_budget')==='on',contracts_ready:f.get('contracts_ready')==='on',procurement_ready:f.get('procurement_ready')==='on',project_team_ready:f.get('project_team_ready')==='on',first_disbursement_ready:f.get('first_disbursement_ready')==='on',execution_start_date:f.get('execution_start_date')||null,notes:String(f.get('notes')||''),updated_at:new Date().toISOString()};const{error}=await s.from('project_execution_controls').update(payload).eq('application_id',application_id);if(error)throw new Error(error.message);revalidatePath('/admin/applications/'+application_id)}
