'use server'
import {revalidatePath} from 'next/cache'
import {redirect} from 'next/navigation'
import {createClient} from '@/lib/supabase/server'
import {isStaffRole} from '@/lib/auth/roles'
async function staff(){const s=await createClient();const{data:c}=await s.auth.getClaims();const uid=c?.claims?.sub as string|undefined;if(!uid)redirect('/login');const{data:p}=await s.from('profiles').select('role').eq('id',uid).maybeSingle();if(!isStaffRole(p?.role)||!['admin','legal','contract_manager','executive','cfo'].includes(p.role))redirect('/admin');return{s,uid}}
export async function initializeClosingRequirements(f:FormData){const{s}=await staff();const application_id=String(f.get('application_id'));const{error}=await s.rpc('initialize_legal_closing_requirements',{p_application_id:application_id});if(error)throw new Error(error.message);revalidatePath('/admin/applications/'+application_id)}
export async function requestSignature(f:FormData){const{s,uid}=await staff();const delivery_id=String(f.get('delivery_id'));const application_id=String(f.get('application_id'));const{data:d}=await s.from('project_document_deliveries').select('id,client_id,title,status').eq('id',delivery_id).maybeSingle();if(!d)throw new Error('Delivery not found');if(!['sent','viewed'].includes(d.status))throw new Error('Document must be sent before signature request');const{data:c}=await s.from('clients').select('legal_name,contact_name,email,user_id').eq('id',d.client_id).maybeSingle();if(!c?.email)throw new Error('Signer email is required');const{error}=await s.from('document_signature_requests').upsert({delivery_id,application_id,signer_user_id:c.user_id||null,signer_name:c.legal_name||c.contact_name||'Authorized signer',signer_email:c.email,provider:'internal_pending',status:'sent',requested_by:uid,sent_at:new Date().toISOString()},{onConflict:'delivery_id'});if(error)throw new Error(error.message);revalidatePath('/admin/applications/'+application_id)}
export async function markSignatureStatus(f:FormData){const{s}=await staff();const id=String(f.get('id'));const status=String(f.get('status'));if(!['sent','viewed','signed','declined','expired','void'].includes(status))throw new Error('Invalid signature status');const patch:any={status};if(status==='viewed')patch.viewed_at=new Date().toISOString();if(status==='signed')patch.signed_at=new Date().toISOString();const{data:req,error}=await s.from('document_signature_requests').update(patch).eq('id',id).select('application_id,delivery_id').maybeSingle();if(error)throw new Error(error.message);if(req){const{data:d}=await s.from('project_document_deliveries').select('document_type').eq('id',req.delivery_id).maybeSingle();if(d?.document_type){const next=status==='signed'?'signed':status==='sent'?'sent':status==='viewed'?'sent':status==='declined'?'pending':status==='expired'?'pending':'pending';await s.from('legal_closing_requirements').update({status:next,signature_request_id:id}).eq('application_id',req.application_id).eq('document_type',d.document_type)}}revalidatePath('/admin/applications/'+String(f.get('application_id')))}
