'use server'
import { revalidatePath } from 'next/cache'
import { redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'
import { isStaffRole } from '@/lib/auth/roles'
async function staff(roles:string[]=[]){const s=await createClient();const {data:c}=await s.auth.getClaims();const uid=c?.claims?.sub as string|undefined;if(!uid)redirect('/login');const {data:p}=await s.from('profiles').select('role').eq('id',uid).maybeSingle();if(!isStaffRole(p?.role)||(roles.length&&!roles.includes(p.role)))redirect('/admin');return{s,uid}}
const n=(v:FormDataEntryValue|null)=>v==null||v===''?null:Number(v)
export async function saveTermSheet(f:FormData){const {s,uid}=await staff();const application_id=String(f.get('application_id'));const patch={application_id,structure_type:String(f.get('structure_type')||'financing'),amount:n(f.get('amount')),currency:String(f.get('currency')||'USD'),sponsor_equity_pct:n(f.get('sponsor_equity_pct')),banquisqueya_equity_pct:n(f.get('banquisqueya_equity_pct')),third_party_capital:n(f.get('third_party_capital')),development_fee_pct:n(f.get('development_fee_pct')),management_fee_pct:n(f.get('management_fee_pct')),term_months:n(f.get('term_months')),interest_rate:n(f.get('interest_rate')),repayment_structure:String(f.get('repayment_structure')||''),use_of_funds:String(f.get('use_of_funds')||''),conditions_precedent:String(f.get('conditions_precedent')||''),closing_conditions:String(f.get('closing_conditions')||''),validity_days:n(f.get('validity_days'))||15,status:String(f.get('status')||'draft'),prepared_by:uid};const {error}=await s.from('project_term_sheets').upsert(patch,{onConflict:'application_id'});if(error)throw new Error(error.message);revalidatePath('/admin/applications/'+application_id)}
export async function updateTermSheetStatus(f:FormData){const {s,uid}=await staff(['admin','legal','executive','cfo']);const id=String(f.get('id'));const status=String(f.get('status'));const patch:any={status,updated_at:new Date().toISOString()};if(status==='approved_internal'){patch.approved_by=uid;patch.approved_at=new Date().toISOString()}if(status==='issued')patch.issued_at=new Date().toISOString();const {error}=await s.from('project_term_sheets').update(patch).eq('id',id);if(error)throw new Error(error.message);revalidatePath('/admin/applications/'+String(f.get('application_id')))}
export async function addLegalWorkflow(f:FormData){const {s,uid}=await staff(['admin','legal','contract_manager','executive']);const application_id=String(f.get('application_id'));const {error}=await s.from('project_legal_workflows').insert({application_id,document_type:String(f.get('document_type')),title:String(f.get('title')),version:String(f.get('version')||'1.0'),counterparty_name:String(f.get('counterparty_name')||''),notes:String(f.get('notes')||''),status:'draft',prepared_by:uid});if(error)throw new Error(error.message);revalidatePath('/admin/applications/'+application_id)}
export async function updateLegalWorkflow(f:FormData){const {s,uid}=await staff(['admin','legal','contract_manager','executive']);const id=String(f.get('id'));const status=String(f.get('status'));const patch:any={status,updated_at:new Date().toISOString()};if(status==='approved')patch.approved_by=uid;if(status==='legal_review')patch.reviewed_by=uid;if(status==='sent')patch.sent_at=new Date().toISOString();if(status==='accepted')patch.accepted_at=new Date().toISOString();if(status==='executed')patch.executed_at=new Date().toISOString();const {error}=await s.from('project_legal_workflows').update(patch).eq('id',id);if(error)throw new Error(error.message);revalidatePath('/admin/applications/'+String(f.get('application_id')))}