'use server'
import { revalidatePath } from 'next/cache'
import { redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'
import { isStaffRole } from '@/lib/auth/roles'
async function staff(){const s=await createClient();const {data:c}=await s.auth.getClaims();const uid=c?.claims?.sub as string|undefined;if(!uid)redirect('/login');const {data:p}=await s.from('profiles').select('role').eq('id',uid).maybeSingle();if(!isStaffRole(p?.role))redirect('/admin');return {s,uid}}
export async function createCapitalSource(f:FormData){const {s,uid}=await staff();const {error}=await s.from('capital_sources').insert({name:String(f.get('name')||''),source_type:String(f.get('source_type')||'private_capital'),jurisdiction:String(f.get('jurisdiction')||''),contact:String(f.get('contact')||''),status:String(f.get('status')||'prospect'),notes:String(f.get('notes')||''),created_by:uid});if(error)throw new Error(error.message);revalidatePath('/admin/capital-sources')}
export async function updateCapitalSource(f:FormData){const {s}=await staff();const id=String(f.get('id'));const {error}=await s.from('capital_sources').update({name:String(f.get('name')||''),source_type:String(f.get('source_type')||'private_capital'),jurisdiction:String(f.get('jurisdiction')||''),contact:String(f.get('contact')||''),status:String(f.get('status')||'prospect'),notes:String(f.get('notes')||'')}).eq('id',id);if(error)throw new Error(error.message);revalidatePath('/admin/capital-sources')}
export async function saveCapitalMandate(f:FormData){const {s}=await staff();const capital_source_id=String(f.get('capital_source_id'));const existing=await s.from('capital_relationships').select('id').eq('capital_source_id',capital_source_id).maybeSingle();const payload={capital_source_id,relationship_status:String(f.get('relationship_status')||'prospect'),relationship_type:String(f.get('relationship_type')||'institutional_capital'),preferred_sectors:String(f.get('preferred_sectors')||'').split(',').map(x=>x.trim()).filter(Boolean),preferred_jurisdictions:String(f.get('preferred_jurisdictions')||'').split(',').map(x=>x.trim()).filter(Boolean),preferred_subsectors:String(f.get('preferred_subsectors')||'').split(',').map(x=>x.trim()).filter(Boolean),preferred_stages:String(f.get('preferred_stages')||'').split(',').map(x=>x.trim()).filter(Boolean),preferred_currencies:String(f.get('preferred_currencies')||'USD').split(',').map(x=>x.trim()).filter(Boolean),ticket_min:Number(f.get('ticket_min'))||0,ticket_max:Number(f.get('ticket_max'))||0,currency:String(f.get('currency')||'USD'),investment_horizon:String(f.get('investment_horizon')||''),instrument_preferences:String(f.get('instrument_preferences')||'').split(',').map(x=>x.trim()).filter(Boolean),mandate_notes:String(f.get('mandate_notes')||''),mandate_active:f.get('mandate_active')==='on'};const q=existing.data?.id?s.from('capital_relationships').update(payload).eq('id',existing.data.id):s.from('capital_relationships').insert(payload);const {error}=await q;if(error)throw new Error(error.message);revalidatePath('/admin/capital-sources')}
