import { createClient } from '@/lib/supabase/server'
import { createCapitalSource, updateCapitalSource } from './actions'
const types=['bank','institutional','family_office','fund','private_capital','multilateral','development_finance','strategic_investor','financial_platform','guarantee','sblc_collateral','other']
const statuses=['prospect','kyc_review','verified','active','inactive','rejected']
export default async function CapitalSourcesPage(){
 const s=await createClient(); const {data:sources}=await s.from('capital_sources').select('*').order('created_at',{ascending:false})
 return <div className="dashboard"><div className="container dashboard-wide"><div className="dashboard-heading"><div><div className="eyebrow">CAPITAL & TREASURY</div><h1>Fuentes de capital</h1><p className="muted">Registro institucional de bancos, fondos, family offices, capital privado y otras fuentes sujetas a KYC, verificación y documentación.</p></div></div>
 <div className="card form" style={{marginBottom:22}}><h2>Registrar fuente</h2><form action={createCapitalSource}><div className="grid"><label>Nombre<input name="name" required/></label><label>Tipo<select name="source_type">{types.map(x=><option key={x} value={x}>{x.replaceAll('_',' ')}</option>)}</select></label><label>Jurisdicción<input name="jurisdiction"/></label><label>Contacto<input name="contact"/></label></div><label>Notas<textarea name="notes"/></label><button className="btn primary">Guardar fuente</button></form></div>
 <div className="panel"><div className="panel-heading"><div><h2>Pipeline de capital</h2><p className="muted">Las fuentes permanecen como registros de originación hasta completar la debida diligencia y verificaciones aplicables.</p></div></div><div className="table-wrap"><table className="table professional-table"><thead><tr><th>Fuente</th><th>Tipo</th><th>Jurisdicción</th><th>Estado</th><th>Contacto</th><th>Actualizar</th></tr></thead><tbody>{(sources||[]).map(x=><tr key={x.id}><td><strong>{x.name}</strong></td><td>{x.source_type?.replaceAll('_',' ')}</td><td>{x.jurisdiction||'—'}</td><td><span className="status-chip">{x.status}</span></td><td>{x.contact||'—'}</td><td><details><summary>Editar</summary><form action={updateCapitalSource} className="form card" style={{marginTop:10}}><input type="hidden" name="id" value={x.id}/><input name="name" defaultValue={x.name}/><select name="source_type" defaultValue={x.source_type}>{types.map(t=><option key={t} value={t}>{t.replaceAll('_',' ')}</option>)}</select><input name="jurisdiction" defaultValue={x.jurisdiction||''}/><input name="contact" defaultValue={x.contact||''}/><select name="status" defaultValue={x.status}>{statuses.map(t=><option key={t} value={t}>{t.replaceAll('_',' ')}</option>)}</select><textarea name="notes" defaultValue={x.notes||''}/><button className="btn primary">Actualizar</button></form></details></td></tr>)}</tbody></table></div></div></div></div>
}