'use server'
import { revalidatePath } from 'next/cache'
import { redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'
import { isStaffRole } from '@/lib/auth/roles'
async function staff(){const s=await createClient();const{data:c}=await s.auth.getClaims();const uid=c?.claims?.sub as string|undefined;if(!uid)redirect('/login');const{data:p}=await s.from('profiles').select('role').eq('id',uid).maybeSingle();if(!isStaffRole(p?.role))redirect('/admin');return{s,uid,role:p.role}}
export async function initializeDeployment(f:FormData){const{s}=await staff();const project_id=String(f.get('project_id'));const{error}=await s.rpc('initialize_financial_deployment',{p_project_id:project_id,p_application_id:f.get('application_id')||null});if(error)throw new Error(error.message);revalidatePath('/admin/projects/'+project_id+'/deployment')}
export async function updateDeploymentControl(f:FormData){const{s,uid,role}=await staff();if(!['admin','finance','cfo','executive'].includes(role))throw new Error('Solo Finanzas/CFO/Ejecutivo/Admin puede aprobar deployment.');const project_id=String(f.get('project_id'));const payload={status:String(f.get('status')),capital_close_confirmed:String(f.get('capital_close_confirmed'))==='yes',spv_confirmed:String(f.get('spv_confirmed'))==='yes',contracts_confirmed:String(f.get('contracts_confirmed'))==='yes',budget_confirmed:String(f.get('budget_confirmed'))==='yes',bank_account_confirmed:String(f.get('bank_account_confirmed'))==='yes',disbursement_conditions_confirmed:String(f.get('disbursement_conditions_confirmed'))==='yes',first_disbursement_amount:Number(f.get('first_disbursement_amount')||0),first_disbursement_currency:String(f.get('first_disbursement_currency')||'USD'),approved_by:['approved','first_disbursement','in_deployment'].includes(String(f.get('status')))?uid:null,approved_at:['approved','first_disbursement','in_deployment'].includes(String(f.get('status')))?new Date().toISOString():null,notes:String(f.get('notes')||'')};const{error}=await s.from('project_deployment_controls').update(payload).eq('project_id',project_id);if(error)throw new Error(error.message);revalidatePath('/admin/projects/'+project_id+'/deployment')}
export async function saveTranche(f:FormData){const{s,uid,role}=await staff();if(!['admin','finance','cfo','executive'].includes(role))throw new Error('Rol no autorizado.');const project_id=String(f.get('project_id'));const{error}=await s.from('project_deployment_tranches').upsert({project_id,application_id:f.get('application_id')||null,tranche_number:Number(f.get('tranche_number')),name:String(f.get('name')),amount:Number(f.get('amount')),currency:String(f.get('currency')||'USD'),release_condition:String(f.get('release_condition')||''),status:String(f.get('status')||'planned'),approved_by:['approved','ready'].includes(String(f.get('status')))?uid:null,approved_at:['approved','ready'].includes(String(f.get('status')))?new Date().toISOString():null,notes:String(f.get('notes')||'')},{onConflict:'project_id,tranche_number'});if(error)throw new Error(error.message);revalidatePath('/admin/projects/'+project_id+'/deployment')}
