'use server'
import { revalidatePath } from 'next/cache'
import { redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'
import { isStaffRole } from '@/lib/auth/roles'
async function staff(){const s=await createClient();const{data:c}=await s.auth.getClaims();const uid=c?.claims?.sub as string|undefined;if(!uid)redirect('/login');const{data:p}=await s.from('profiles').select('role').eq('id',uid).maybeSingle();if(!isStaffRole(p?.role))redirect('/admin');return{s,uid,role:p.role}}
export async function initializeExecution(f:FormData){const{s}=await staff();const project_id=String(f.get('project_id'));const{error}=await s.rpc('initialize_project_execution',{p_project_id:project_id,p_application_id:f.get('application_id')||null});if(error)throw new Error(error.message);revalidatePath('/admin/projects/'+project_id+'/execution')}
export async function updateWorkstream(f:FormData){const{s}=await staff();const id=String(f.get('id'));const{error}=await s.from('project_execution_workstreams').update({status:String(f.get('status')),progress_pct:Number(f.get('progress_pct')||0),planned_start:f.get('planned_start')||null,planned_end:f.get('planned_end')||null,actual_start:f.get('actual_start')||null,actual_end:f.get('actual_end')||null,budget:Number(f.get('budget')||0),committed:Number(f.get('committed')||0),spent:Number(f.get('spent')||0),notes:String(f.get('notes')||'')}).eq('id',id);if(error)throw new Error(error.message);revalidatePath('/admin/projects/'+String(f.get('project_id'))+'/execution')}
export async function saveAction(f:FormData){const{s,uid}=await staff();const project_id=String(f.get('project_id'));const{error}=await s.from('project_execution_actions').insert({project_id,application_id:f.get('application_id')||null,workstream_id:f.get('workstream_id')||null,action_type:String(f.get('action_type')||'execution'),title:String(f.get('title')),description:String(f.get('description')||''),priority:String(f.get('priority')||'medium'),owner_id:f.get('owner_id')||uid,due_date:f.get('due_date')||null,created_by:uid});if(error)throw new Error(error.message);revalidatePath('/admin/projects/'+project_id+'/execution')}
export async function updateAction(f:FormData){const{s}=await staff();const id=String(f.get('id'));const{error}=await s.from('project_execution_actions').update({status:String(f.get('status')),priority:String(f.get('priority')||'medium'),due_date:f.get('due_date')||null}).eq('id',id);if(error)throw new Error(error.message);revalidatePath('/admin/projects/'+String(f.get('project_id'))+'/execution')}
