import { createClient } from '@/lib/supabase/server'
import { redirect } from 'next/navigation'
import { uploadReferrerDocument, savePaymentAccount } from './actions'

const labels:Record<string,string>={identity_document:'Pasaporte / ID oficial',bank_reference:'Referencia bancaria',proof_of_address:'Comprobante de domicilio',tax_document:'Documento fiscal',corporate_document:'Documento corporativo',other:'Otro'}

export default async function ReferrerKyc(){
 const s=await createClient(); const {data:c}=await s.auth.getClaims(); const uid=c?.claims?.sub as string|undefined
 if(!uid) redirect('/login')
 const {data:r}=await s.from('referrers').select('id,contact_name,legal_name,status,kyc_status').eq('user_id',uid).maybeSingle()
 if(!r) redirect('/referidor/registro')
 const [{data:docs},{data:accounts}]=await Promise.all([
   s.from('referrer_documents').select('id,document_type,file_name,status,uploaded_at,review_notes').eq('referrer_id',r.id).order('uploaded_at',{ascending:false}),
   s.from('referrer_payment_accounts').select('id,account_holder_name,bank_name,bank_country,account_number_last4,iban,swift_bic,routing_number,currency,status,verification_notes').eq('referrer_id',r.id).order('created_at',{ascending:false})
 ])
 return <main className="dashboard-wide"><div className="dashboard-heading"><div><div className="eyebrow">REFERRER NETWORK · KYC & PAYMENT PROFILE</div><h1>Expediente de cumplimiento</h1><p className="muted">Antes de aprobar tu registro, BanQuisqueya & Trust debe verificar tu identidad y la cuenta bancaria donde recibirás las comisiones.</p></div></div>
 <section className="panel"><h2>Documentación obligatoria</h2><p className="muted">Se requiere al menos un documento de identidad oficial vigente y una referencia bancaria. Los documentos son privados y sólo estarán disponibles para personal autorizado.</p><form action={uploadReferrerDocument} className="form" encType="multipart/form-data"><label>Tipo de documento<select name="document_type" required><option value="identity_document">Pasaporte / ID oficial</option><option value="bank_reference">Referencia bancaria</option><option value="proof_of_address">Comprobante de domicilio</option><option value="tax_document">Documento fiscal</option><option value="corporate_document">Documento corporativo</option><option value="other">Otro</option></select></label><label>Archivo<input name="file" type="file" accept=".pdf,.jpg,.jpeg,.png,.webp" required/></label><button className="btn primary">Cargar documento</button></form>
 <div className="table-wrap" style={{marginTop:20}}><table className="professional-table"><thead><tr><th>Documento</th><th>Archivo</th><th>Estado</th><th>Fecha</th></tr></thead><tbody>{(docs||[]).map(d=><tr key={d.id}><td>{labels[d.document_type]||d.document_type}</td><td>{d.file_name}</td><td>{d.status}</td><td>{new Date(d.uploaded_at).toLocaleDateString('es-DO')}</td></tr>)}{!docs?.length&&<tr><td colSpan={4}>Aún no has cargado documentos.</td></tr>}</tbody></table></div></section>
 <section className="panel" style={{marginTop:20}}><h2>Cuenta para pago de comisiones</h2><p className="muted">La información bancaria será verificada contra la referencia bancaria presentada. El pago sólo podrá realizarse a una cuenta aprobada en este expediente.</p><form action={savePaymentAccount} className="form"><div className="grid"><label>Titular de la cuenta<input name="account_holder_name" required/></label><label>Banco<input name="bank_name" required/></label><label>País del banco<input name="bank_country" required/></label><label>Moneda<select name="currency"><option>USD</option><option>EUR</option><option>DOP</option><option>GBP</option><option>CHF</option></select></label><label>Últimos 4 dígitos<input name="account_number_last4" inputMode="numeric" maxLength={4} pattern="[0-9]{4}" placeholder="1234"/></label><label>IBAN<input name="iban"/></label><label>SWIFT / BIC<input name="swift_bic"/></label><label>ABA / Routing<input name="routing_number"/></label></div><button className="btn primary">Registrar cuenta para comisiones</button></form>
 <div className="table-wrap" style={{marginTop:20}}><table className="professional-table"><thead><tr><th>Banco</th><th>Titular</th><th>Cuenta</th><th>Estado</th></tr></thead><tbody>{(accounts||[]).map(a=><tr key={a.id}><td>{a.bank_name}<br/><span className="muted">{a.bank_country}</span></td><td>{a.account_holder_name}</td><td>{a.iban||a.routing_number||a.account_number_last4?'•••• '+(a.account_number_last4||''):'—'}</td><td>{a.status}</td></tr>)}{!accounts?.length&&<tr><td colSpan={4}>Aún no has registrado una cuenta.</td></tr>}</tbody></table></div></section>
 <section className="notice-panel" style={{marginTop:20}}><div><strong>Condición de aprobación</strong><p>El estado de Referidor no podrá pasar a Aprobado hasta que Compliance valide la identidad, la referencia bancaria y la cuenta destinada al pago de comisiones.</p></div></section>
 </main>
}
