'use server'
import { revalidatePath } from 'next/cache'
import { redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'
import { isStaffRole } from '@/lib/auth/roles'
async function staff(){const s=await createClient();const{data:c}=await s.auth.getClaims();const uid=c?.claims?.sub as string|undefined;if(!uid)redirect('/login');const{data:p}=await s.from('profiles').select('role').eq('id',uid).maybeSingle();if(!isStaffRole(p?.role))redirect('/admin');return{s,uid}}
export async function createSprint(f:FormData){const{s,uid}=await staff();const project_id=String(f.get('project_id'));const{data:mx}=await s.from('project_agile_sprints').select('sprint_number').eq('project_id',project_id).order('sprint_number',{ascending:false}).limit(1).maybeSingle();const{error}=await s.from('project_agile_sprints').insert({project_id,sprint_number:(mx?.sprint_number||0)+1,name:String(f.get('name')),goal:String(f.get('goal')||''),start_date:f.get('start_date')||null,end_date:f.get('end_date')||null,owner_id:uid,created_by:uid});if(error)throw new Error(error.message);revalidatePath('/admin/projects/'+project_id)}
export async function createBacklogItem(f:FormData){const{s,uid}=await staff();const project_id=String(f.get('project_id'));const{error}=await s.from('project_agile_backlog').insert({project_id,sprint_id:f.get('sprint_id')||null,item_type:String(f.get('item_type')||'work_package'),epic:String(f.get('epic')||''),title:String(f.get('title')),description:String(f.get('description')||''),priority:String(f.get('priority')||'medium'),story_points:Number(f.get('story_points')||0),due_date:f.get('due_date')||null,created_by:uid,owner_id:uid});if(error)throw new Error(error.message);revalidatePath('/admin/projects/'+project_id)}
export async function updateBacklogStatus(f:FormData){const{s}=await staff();const id=String(f.get('id'));const project_id=String(f.get('project_id'));const{error}=await s.from('project_agile_backlog').update({status:String(f.get('status'))}).eq('id',id);if(error)throw new Error(error.message);revalidatePath('/admin/projects/'+project_id)}
export async function saveReadinessItem(f:FormData){const{s}=await staff();const project_id=String(f.get('project_id'));const{error}=await s.from('project_readiness_items').insert({project_id,category:String(f.get('category')),item:String(f.get('item')),status:String(f.get('status')||'not_started'),evidence_note:String(f.get('evidence_note')||''),due_date:f.get('due_date')||null});if(error)throw new Error(error.message);revalidatePath('/admin/projects/'+project_id)}
export async function saveStageGate(f:FormData){const{s}=await staff();const project_id=String(f.get('project_id'));const gate_number=Number(f.get('gate_number'));const{error}=await s.from('project_stage_gates').upsert({project_id,gate_number,name:String(f.get('name')),description:String(f.get('description')||''),status:String(f.get('status')||'pending'),decision_notes:String(f.get('decision_notes')||'')},{onConflict:'project_id,gate_number'});if(error)throw new Error(error.message);revalidatePath('/admin/projects/'+project_id)}

export async function initializeDueDiligence(f:FormData){const{s}=await staff();const project_id=String(f.get('project_id'));const application_id=f.get('application_id')||null;const{error}=await s.rpc('initialize_due_diligence',{p_project_id:project_id,p_application_id:application_id});if(error)throw new Error(error.message);revalidatePath('/admin/projects/'+project_id+'/agile');revalidatePath('/admin/projects/'+project_id+'/dd')}
export async function updateDDWorkstream(f:FormData){const{s,uid}=await staff();const id=String(f.get('id'));const project_id=String(f.get('project_id'));const status=String(f.get('status'));const{error}=await s.from('project_dd_workstreams').update({status,findings:String(f.get('findings')||''),key_risks:String(f.get('key_risks')||''),conditions:String(f.get('conditions')||''),verified_by:status==='verified'||status==='complete'?uid:null,verified_at:status==='verified'||status==='complete'?new Date().toISOString():null}).eq('id',id);if(error)throw new Error(error.message);revalidatePath('/admin/projects/'+project_id+'/dd')}
