'use server'
import { revalidatePath } from 'next/cache'
import { redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'
import { isStaffRole } from '@/lib/auth/roles'
async function staff(){const s=await createClient();const {data:c}=await s.auth.getClaims();const uid=c?.claims?.sub as string|undefined;if(!uid)redirect('/login');const {data:p}=await s.from('profiles').select('role').eq('id',uid).maybeSingle();if(!isStaffRole(p?.role))redirect('/admin');return{s,uid}}
export async function uploadProjectDocument(f:FormData){const{s,uid}=await staff();const project_id=String(f.get('project_id'));const file=f.get('file') as File;if(!file||!file.size)throw new Error('Debe seleccionar un archivo.');if(file.size>26214400)throw new Error('El archivo supera 25 MB.');const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_');const path=project_id+'/'+crypto.randomUUID()+'-'+safe;const{error:up}=await s.storage.from('project-documents').upload(path,file,{contentType:file.type,upsert:false});if(up)throw new Error(up.message);const{data:d,error}=await s.from('project_document_register').insert({project_id,title:String(f.get('title')),document_type:String(f.get('document_type')),confidentiality:String(f.get('confidentiality')||'internal'),status:'draft',current_version:1,storage_path:'project-documents/'+path,created_by:uid}).select('id').single();if(error)throw new Error(error.message);const{error:ve}=await s.from('project_document_register_versions').update({storage_path:'project-documents/'+path,file_name:file.name,status:'draft'}).eq('document_id',d.id).eq('version',1);if(ve)throw new Error(ve.message);revalidatePath('/admin/projects/'+project_id);revalidatePath('/admin/projects/'+project_id+'/documents')}
export async function approveDocumentVersion(f:FormData){const{s,uid}=await staff();const document_id=String(f.get('document_id'));const version=Number(f.get('version')||1);const{error}=await s.from('project_document_register_versions').update({status:'approved',approved_by:uid,approved_at:new Date().toISOString()}).eq('document_id',document_id).eq('version',version);if(error)throw new Error(error.message);const{data:d}=await s.from('project_document_register').select('project_id').eq('id',document_id).single();if(d){await s.from('project_document_register').update({status:'approved',current_version:version}).eq('id',document_id);revalidatePath('/admin/projects/'+d.project_id)}}
export async function registerDocument(f:FormData){const{s,uid}=await staff();const project_id=String(f.get('project_id'));const application_id=f.get('application_id')||null;const{data:d,error}=await s.from('project_document_register').insert({project_id,application_id,document_type:String(f.get('document_type')||'other'),title:String(f.get('title')),description:String(f.get('description')||''),status:String(f.get('status')||'required'),due_date:f.get('due_date')||null,confidentiality:String(f.get('confidentiality')||'internal'),created_by:uid}).select('id').single();if(error)throw new Error(error.message);const{error:ve}=await s.from('project_document_register_versions').insert({document_id:d.id,version:1,status:'draft',prepared_by:uid});if(ve)throw new Error(ve.message);revalidatePath('/admin/projects/'+project_id)}
