import Link from 'next/link'
import { notFound } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'
import { updateProject } from '../actions'
import { saveMilestone, saveExecutionUpdate } from './execution-actions'
import { saveRisk, saveIssue, saveDecision } from './pmo-actions'
import { registerDocument } from './document-actions'
import { refreshMatches, updateMatch } from '../../capital-matching/actions'
import CapitalCommunications from './capital-communications'

export default async function ProjectDetail({params}:{params:Promise<{id:string}>}){
 const {id}=await params; const s=await createClient()
 const [{data:p},{data:dash},{data:fin},{data:milestones},{data:updates},{data:exec},{data:risks},{data:issues},{data:decisions},{data:documents},{data:matches},{data:capitalCommunications},{data:disbControl}]=await Promise.all([
  s.from('projects').select('*').eq('id',id).maybeSingle(),
  s.from('project_execution_dashboard').select('*').eq('project_id',id).maybeSingle(),
  s.from('project_execution_financial_dashboard').select('*').eq('project_id',id).maybeSingle(),
  s.from('project_execution_milestones').select('*').eq('project_id',id).order('planned_date',{ascending:true}),
  s.from('project_execution_updates').select('*').eq('project_id',id).order('report_date',{ascending:false}).limit(10),
  s.from('project_execution_controls').select('*').eq('project_id',id).maybeSingle(),
  s.from('project_risk_register').select('*').eq('project_id',id).order('score',{ascending:false}).limit(10),
  s.from('project_issues').select('*').eq('project_id',id).order('created_at',{ascending:false}).limit(10),
  s.from('project_decisions').select('*').eq('project_id',id).order('created_at',{ascending:false}).limit(10),
  s.from('project_document_register').select('*').eq('project_id',id).order('created_at',{ascending:false}),
  s.from('capital_matching_dashboard').select('*').eq('project_id',id).order('match_score',{ascending:false}),
  s.from('project_capital_communications').select('*').eq('project_id',id).order('created_at',{ascending:false}).limit(10),
  s.from('project_disbursement_execution_control').select('*').eq('project_id',id).maybeSingle()
 ])
 if(!p)notFound()
 const money=(n:number)=>'USD '+Number(n||0).toLocaleString('en-US',{maximumFractionDigits:0})
 const capitalMatches=matches||[]
 const communications=capitalCommunications||[]

 return <div className="dashboard"><div className="container">
  <Link href="/admin/projects">← Proyectos</Link>
  <div style={{margin:'16px 0 24px'}}><div className="muted">Ficha y Command Center</div><h1>{p.name}</h1><p className="muted">{p.sector} · {p.location||'Ubicación no definida'} · {p.status}</p></div>
  {dash&&<div className="metric-grid">
   <div className="metric-card"><div className="metric-label">Presupuesto</div><div className="metric-value">{money(dash.budget)}</div></div>
   <div className="metric-card"><div className="metric-label">Comprometido</div><div className="metric-value">{money(dash.committed)}</div></div>
   <div className="metric-card"><div className="metric-label">Financiado</div><div className="metric-value">{money(dash.funded)}</div></div>
   <div className="metric-card"><div className="metric-label">Funding gap</div><div className="metric-value">{money(dash.funding_gap)}</div></div>
  </div>}
  {fin&&<div className="metric-grid" style={{marginTop:20}}><div className="metric-card"><div className="metric-label">Órdenes de compra</div><div className="metric-value">{fin.purchase_order_count}</div><div className="metric-caption">{money(fin.purchase_order_value)}</div></div><div className="metric-card"><div className="metric-label">Cubicaciones aprobadas</div><div className="metric-value">{fin.approved_cubicaciones}</div><div className="metric-caption">{money(fin.approved_cubicacion_value)}</div></div><div className="metric-card"><div className="metric-label">Desembolsos pagados</div><div className="metric-value">{fin.paid_disbursements}</div><div className="metric-caption">{money(fin.paid_value)}</div></div><div className="metric-card"><div className="metric-label">Disponible presupuesto</div><div className="metric-value">{money(fin.remaining_budget)}</div></div></div>}
  <section className="panel" style={{marginTop:20}}><div className="panel-heading"><div><div className="eyebrow">DISBURSEMENT → EXECUTION</div><h2>Control de desembolsos y movilización</h2><p className="muted">El primer desembolso pagado habilita el avance operativo desde movilización, sujeto a los controles de ejecución existentes.</p></div><span className="status-chip">{disbControl?.execution_status||exec?.status||'—'}</span></div><div className="metric-grid"><div className="metric-card"><div className="metric-label">Primer desembolso</div><div className="metric-value">{disbControl?.first_disbursement_ready?'READY':'PENDING'}</div></div><div className="metric-card"><div className="metric-label">Desembolsado</div><div className="metric-value">{money(disbControl?.total_disbursed)}</div></div><div className="metric-card"><div className="metric-label">Pendiente de pago</div><div className="metric-value">{money(disbControl?.pending_disbursement)}</div></div><div className="metric-card"><div className="metric-label">Pagos realizados</div><div className="metric-value">{disbControl?.paid_disbursements||0}</div></div></div></section>
<div className="dashboard-columns" style={{marginTop:20}}>
   <section className="panel"><div className="panel-heading"><div><div className="eyebrow">Ejecución</div><h2>Avance del proyecto</h2></div></div>
    <div className="pipeline-list"><div className="pipeline-track"><span style={{width:(dash?.physical_progress||0)+'%'}}/></div><strong>Avance físico: {Number(dash?.physical_progress||0).toFixed(1)}%</strong><div className="pipeline-track"><span style={{width:(dash?.financial_progress||0)+'%'}}/></div><strong>Avance financiero: {Number(dash?.financial_progress||0).toFixed(1)}%</strong></div>
    <p className="muted">Hitos retrasados: {dash?.delayed_milestones||0} · Última actualización: {dash?.last_update||'—'}</p>
   </section>
   <section className="panel"><div className="panel-heading"><div><div className="eyebrow">Control</div><h2>Estado operativo</h2></div></div><p><strong>{exec?.status||'No inicializado'}</strong></p><p>Presupuesto: {exec?.approved_budget?'✓':'Pendiente'} · Contratos: {exec?.contracts_ready?'✓':'Pendiente'} · Procurement: {exec?.procurement_ready?'✓':'Pendiente'} · Equipo: {exec?.project_team_ready?'✓':'Pendiente'} · Primer desembolso: {exec?.first_disbursement_ready?'✓':'Pendiente'}</p></section>
  </div>
  <div className="dashboard-columns" style={{marginTop:20}}>
   <section className="panel"><div className="panel-heading"><h2>Registrar actualización</h2></div><form action={saveExecutionUpdate} className="form"><input type="hidden" name="project_id" value={id}/><div className="grid"><label>Fecha<input name="report_date" type="date"/></label><label>Avance físico %<input name="physical_progress_pct" type="number" step="0.1" min="0" max="100"/></label><label>Avance financiero %<input name="financial_progress_pct" type="number" step="0.1" min="0" max="100"/></label><label>Gastado<input name="amount_spent" type="number" step="0.01"/></label><label>Comprometido<input name="amount_committed" type="number" step="0.01"/></label><label>Moneda<input name="currency" defaultValue="USD"/></label></div><label>Resumen<textarea name="summary"/></label><label>Riesgos<textarea name="risks"/></label><label>Decisiones requeridas<textarea name="decisions_required"/></label><button className="btn primary">Guardar actualización</button></form></section>
   <section className="panel"><div className="panel-heading"><h2>Nuevo hito</h2></div><form action={saveMilestone} className="form"><input type="hidden" name="project_id" value={id}/><input type="hidden" name="application_id" value=""/><label>Hito<input name="name" required/></label><div className="grid"><label>Categoría<input name="category" defaultValue="general"/></label><label>Fecha planificada<input name="planned_date" type="date"/></label><label>Progreso %<input name="progress_pct" type="number" min="0" max="100" defaultValue="0"/></label><label>Estado<select name="status"><option value="pending">Pendiente</option><option value="in_progress">En ejecución</option><option value="completed">Completado</option><option value="delayed">Retrasado</option></select></label></div><label>Notas<textarea name="notes"/></label><button className="btn primary">Agregar hito</button></form></section>
  </div>
<div className="dashboard-columns" style={{marginTop:20}}><section className="panel"><div className="panel-heading"><h2>Risk Register</h2></div><form action={saveRisk} className="form"><input type="hidden" name="project_id" value={id}/><label>Riesgo<input name="title" required/></label><div className="grid"><label>Categoría<input name="category" defaultValue="financial"/></label><label>Probabilidad<select name="probability" defaultValue="3"><option>1</option><option>2</option><option>3</option><option>4</option><option>5</option></select></label><label>Impacto<select name="impact" defaultValue="3"><option>1</option><option>2</option><option>3</option><option>4</option><option>5</option></select></label><label>Fecha objetivo<input name="target_date" type="date"/></label></div><label>Mitigación<textarea name="mitigation_plan"/></label><button className="btn primary">Registrar riesgo</button></form>{(risks||[]).slice(0,5).map((r:any)=><div className="notice-panel" key={r.id}><strong>{r.title}</strong> · Score {r.score} · {r.status}<br/><span className="muted">{r.mitigation_plan||'Sin mitigación registrada'}</span></div>)}</section><section className="panel"><div className="panel-heading"><h2>Issues & Decisions</h2></div><form action={saveIssue} className="form"><input type="hidden" name="project_id" value={id}/><label>Issue<input name="title" required/></label><div className="grid"><label>Prioridad<select name="priority" defaultValue="medium"><option>low</option><option>medium</option><option>high</option><option>critical</option></select></label><label>Fecha límite<input name="due_date" type="date"/></label></div><label>Descripción<textarea name="description"/></label><button className="btn primary">Registrar issue</button></form>{(issues||[]).slice(0,4).map((x:any)=><div className="notice-panel" key={x.id}><strong>{x.title}</strong> · {x.priority} · {x.status}</div>)}<hr/><form action={saveDecision} className="form"><input type="hidden" name="project_id" value={id}/><label>Decisión requerida<input name="title" required/></label><label>Detalle<textarea name="decision_text"/></label><button className="btn primary">Registrar decisión</button></form>{(decisions||[]).slice(0,4).map((d:any)=><div className="notice-panel" key={d.id}><strong>{d.title}</strong> · {d.status}</div>)}</section></div>
<section className="panel" style={{marginTop:20}}><div className="panel-heading"><div><div className="eyebrow">CAPITAL ORIGINATION</div><h2>Capital Matching</h2><p className="muted">Fuentes compatibles según sector, subsector, jurisdicción, ticket, moneda y etapa del proyecto.</p></div><form action={refreshMatches}><input type="hidden" name="project_id" value={id}/><button className="btn primary">Actualizar matching</button></form></div><div className="table-wrap"><table className="professional-table"><thead><tr><th>Fuente</th><th>Sector / Subsector</th><th>Jurisdicción</th><th>Match</th><th>Pipeline</th><th>Acción</th></tr></thead><tbody>{capitalMatches.slice(0,10).map((m:any)=><tr key={m.id}><td><strong>{m.capital_source}</strong><br/><span className="muted">{m.source_type}</span></td><td>{m.sector||'—'}<br/><span className="muted">{m.subsector||'—'}</span></td><td>{m.jurisdiction||'—'}</td><td><strong>{m.match_score}%</strong></td><td><span className="status-chip">{m.status}</span></td><td><form action={updateMatch}><input type="hidden" name="id" value={m.id}/><input type="hidden" name="project_id" value={id}/><input type="hidden" name="status" value={m.status==='identified'?'reviewed':m.status}/><input type="hidden" name="rationale" value={m.rationale||''}/><input type="hidden" name="notes" value={m.notes||''}/><button className="btn">Revisar</button></form></td></tr>)}</tbody></table></div></section>
<CapitalCommunications items={communications}/>
<section className="panel" style={{marginTop:20}}><div className="panel-heading"><div><div className="eyebrow">Document Management</div><h2>Registro documental del proyecto</h2></div></div><form action={registerDocument} className="form"><input type="hidden" name="project_id" value={id}/><label>Título<input name="title" required/></label><div className="grid"><label>Tipo<input name="document_type" placeholder="Contrato, permiso, informe, etc."/></label><label>Fecha límite<input name="due_date" type="date"/></label><label>Confidencialidad<select name="confidentiality"><option>internal</option><option>confidential</option><option>restricted</option><option>public</option></select></label></div><label>Descripción<textarea name="description"/></label><button className="btn primary">Registrar documento</button></form><div className="table-wrap" style={{marginTop:16}}><table className="professional-table"><thead><tr><th>Documento</th><th>Tipo</th><th>Estado</th><th>Versión</th><th>Confidencialidad</th><th>Fecha límite</th></tr></thead><tbody>{(documents||[]).map((d:any)=><tr key={d.id}><td><strong>{d.title}</strong></td><td>{d.document_type}</td><td>{d.status}</td><td>v{d.current_version}</td><td>{d.confidentiality}</td><td>{d.due_date||'—'}</td></tr>)}</tbody></table></div></section><section className="panel" style={{marginTop:20}}><div className="panel-heading"><div><div className="eyebrow">Audit Trail</div><h2>Trazabilidad</h2></div></div><p className="muted">Los cambios relevantes del expediente quedan registrados con usuario, acción, entidad, estado anterior y nuevo estado.</p></section>
  <section className="panel" style={{marginTop:20}}><div className="panel-heading"><h2>Hitos</h2></div><div className="table-wrap"><table className="professional-table"><thead><tr><th>Hito</th><th>Categoría</th><th>Planificado</th><th>Progreso</th><th>Estado</th></tr></thead><tbody>{(milestones||[]).map((m:any)=><tr key={m.id}><td><strong>{m.name}</strong></td><td>{m.category}</td><td>{m.planned_date||'—'}</td><td>{Number(m.progress_pct).toFixed(1)}%</td><td>{m.status}</td></tr>)}</tbody></table></div></section>
  <section className="panel" style={{marginTop:20}}><div className="panel-heading"><h2>Últimas actualizaciones</h2></div><div className="table-wrap"><table className="professional-table"><thead><tr><th>Fecha</th><th>Físico</th><th>Financiero</th><th>Gastado</th><th>Riesgos</th></tr></thead><tbody>{(updates||[]).map((u:any)=><tr key={u.id}><td>{u.report_date}</td><td>{u.physical_progress_pct??'—'}%</td><td>{u.financial_progress_pct??'—'}%</td><td>{money(u.amount_spent)}</td><td>{u.risks||'—'}</td></tr>)}</tbody></table></div></section>
 </div></div>
}