'use server'
import { revalidatePath } from 'next/cache'
import { redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'
import { isStaffRole } from '@/lib/auth/roles'
async function staff(){const s=await createClient();const {data:c}=await s.auth.getClaims();const uid=c?.claims?.sub as string|undefined;if(!uid)redirect('/login');const {data:p}=await s.from('profiles').select('role').eq('id',uid).maybeSingle();if(!isStaffRole(p?.role))redirect('/admin');return{s,uid}}
export async function saveRisk(f:FormData){const{s,uid}=await staff();const project_id=String(f.get('project_id'));const probability=Math.max(1,Math.min(5,Number(f.get('probability')||3)));const impact=Math.max(1,Math.min(5,Number(f.get('impact')||3)));const{error}=await s.from('project_risk_register').insert({project_id,title:String(f.get('title')),description:String(f.get('description')||''),category:String(f.get('category')||'general'),probability,impact,response_strategy:String(f.get('response_strategy')||''),mitigation_plan:String(f.get('mitigation_plan')||''),target_date:f.get('target_date')||null,status:String(f.get('status')||'open'),created_by:uid});if(error)throw new Error(error.message);revalidatePath('/admin/projects/'+project_id)}
export async function saveIssue(f:FormData){const{s,uid}=await staff();const project_id=String(f.get('project_id'));const{error}=await s.from('project_issues').insert({project_id,title:String(f.get('title')),description:String(f.get('description')||''),category:String(f.get('category')||'general'),priority:String(f.get('priority')||'medium'),status:String(f.get('status')||'open'),due_date:f.get('due_date')||null,created_by:uid});if(error)throw new Error(error.message);revalidatePath('/admin/projects/'+project_id)}
export async function saveDecision(f:FormData){const{s,uid}=await staff();const project_id=String(f.get('project_id'));const{error}=await s.from('project_decisions').insert({project_id,title:String(f.get('title')),decision_text:String(f.get('decision_text')||''),decision_date:f.get('decision_date')||null,decision_type:String(f.get('decision_type')||'management'),status:String(f.get('status')||'pending'),created_by:uid});if(error)throw new Error(error.message);revalidatePath('/admin/projects/'+project_id)}
