'use server'
import {createClient} from '@/lib/supabase/server'
import {revalidatePath} from 'next/cache'
async function staff(){const s=await createClient();const {data:c}=await s.auth.getClaims();const uid=c?.claims?.sub as string|undefined;if(!uid)throw new Error('No autorizado');const {data:p}=await s.from('profiles').select('role').eq('id',uid).maybeSingle();if(!['admin','compliance','finance','cfo','executive','relationship_manager','treasury','accounting'].includes(p?.role||''))throw new Error('No autorizado');return s}
export async function approveReferrer(f:FormData){const s=await staff();const {error}=await s.rpc('approve_referrer',{p_referrer_id:String(f.get('id')),p_approved:String(f.get('approved'))==='true',p_notes:String(f.get('notes')||'')||null});if(error)throw new Error(error.message);revalidatePath('/admin/referrers')}
export async function reviewReferral(f:FormData){const s=await staff();const {error}=await s.rpc('review_project_referral',{p_referral_id:String(f.get('id')),p_status:String(f.get('status')),p_project_id:String(f.get('project_id')||'')||null,p_application_id:String(f.get('application_id')||'')||null,p_fee_status:String(f.get('fee_status')||'')||null,p_fee_method:String(f.get('fee_method')||'')||null,p_fee_rate:Number(f.get('fee_rate')||0),p_notes:String(f.get('notes')||'')||null});if(error)throw new Error(error.message);revalidatePath('/admin/referrers')}
export async function reviewCommission(f:FormData){const s=await staff();const {error}=await s.rpc('review_referrer_commission',{p_earning_id:String(f.get('id')),p_status:String(f.get('status')),p_payment_reference:String(f.get('payment_reference')||'')||null});if(error)throw new Error(error.message);revalidatePath('/admin/referrers')}

export async function reviewReferrerDocument(f:FormData){const s=await staff();const {error}=await s.rpc('review_referrer_document',{p_document_id:String(f.get('id')),p_status:String(f.get('status')),p_notes:String(f.get('notes')||'')||null});if(error)throw new Error(error.message);revalidatePath('/admin/referrers')}
export async function reviewReferrerPaymentAccount(f:FormData){const s=await staff();const {error}=await s.rpc('review_referrer_payment_account',{p_account_id:String(f.get('id')),p_status:String(f.get('status')),p_notes:String(f.get('notes')||'')||null});if(error)throw new Error(error.message);revalidatePath('/admin/referrers')}
