'use server'
import { revalidatePath } from 'next/cache'
import { redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'
import { isStaffRole } from '@/lib/auth/roles'

function npv(rate:number,values:number[]){return values.reduce((t,v,i)=>t+v/Math.pow(1+rate,i),0)}
function irr(values:number[]){let r=.1;for(let k=0;k<80;k++){let f=0,df=0;for(let i=0;i<values.length;i++){f+=values[i]/Math.pow(1+r,i);if(i>0)df-=i*values[i]/Math.pow(1+r,i+1)}if(Math.abs(f)<.01)break;if(Math.abs(df)<1e-10)break;r=Math.max(-.99,Math.min(10,r-f/df))}return r}
async function calculate(s:any,project_id:string,m:any){const years=Math.max(1,Math.min(40,Number(m.projection_years)||10));const rev0=Number(m.revenue_annual)||0,op0=Number(m.opex_annual)||0,capex=Number(m.capex)||0,total=Number(m.total_project_cost)||capex,debt0=(Number(m.senior_debt)||0)+(Number(m.mezzanine)||0),equity0=Math.max(0,total-debt0),rg=(Number(m.revenue_growth)||0)/100,og=(Number(m.opex_growth)||0)/100,tax=Number(m.tax_rate)||0,rate=(Number(m.discount_rate)||0),dr=(Number(m.senior_debt_rate)||0)/100,term=Math.max(1,Number(m.senior_debt_term_years)||10),depY=Math.max(1,Number(m.depreciation_years)||10),rows:any[]=[],cfs=[-equity0];let debt=debt0;for(let y=1;y<=years;y++){const rev=rev0*Math.pow(1+rg,y-1),op=op0*Math.pow(1+og,y-1),ebitda=rev-op,dep=capex/depY,ebit=ebitda-dep,interest=debt*dr,principal=y<=term?Math.min(debt,debt0/term):0,taxes=Math.max((ebit-interest)*tax,0),yearCapex=y===1?capex:0,ds=interest+principal,fcf=ebitda-interest-taxes-yearCapex-principal,ecf=fcf;rows.push({project_id,application_id:m.application_id,year_number:y,calendar_year:(Number(m.base_year)||new Date().getFullYear())+y,revenue:rev,opex:op,ebitda,depreciation:dep,ebit,interest_expense:interest,taxes,capex:yearCapex,debt_draw:0,principal_repayment:principal,debt_service:ds,operating_cash_flow:ebitda-interest-taxes,free_cash_flow:fcf,equity_cash_flow:ecf,dscr:ds?(ebitda-taxes)/ds:null});cfs.push(ecf);debt=Math.max(0,debt-principal)}const r=irr([-equity0,...rows.map(x=>x.equity_cash_flow)]),v=npv(rate,[-equity0,...rows.map(x=>x.equity_cash_flow)]),ds=rows.map(x=>x.dscr).filter((x:any)=>x!=null);await s.from('project_financial_cashflows').delete().eq('project_id',project_id);if(rows.length){const{error}=await s.from('project_financial_cashflows').insert(rows);if(error)throw new Error(error.message)}const{error}=await s.from('project_financial_models').update({calculated_irr:r,calculated_npv:v,calculated_dscr:ds.length?Math.min(...ds):null,irr:r,npv:v,dscr:ds.length?Math.min(...ds):null,updated_at:new Date().toISOString(),model_version:(Number(m.model_version)||0)+1}).eq('project_id',project_id);if(error)throw new Error(error.message);return{irr:r,npv:v,dscr:ds.length?Math.min(...ds):null}}
async function staff(){const s=await createClient();const{data:c}=await s.auth.getClaims();const uid=c?.claims?.sub as string|undefined;if(!uid)redirect('/login');const{data:p}=await s.from('profiles').select('role').eq('id',uid).maybeSingle();if(!isStaffRole(p?.role))redirect('/admin');return{s,uid}}
export async function initializeFinancial(f:FormData){const{s}=await staff();const project_id=String(f.get('project_id'));const application_id=f.get('application_id')||null;const{error}=await s.rpc('initialize_financial_structuring',{p_project_id:project_id,p_application_id:application_id});if(error)throw new Error(error.message);revalidatePath('/admin/projects/'+project_id+'/financial')}
export async function saveFinancialModel(f:FormData){const{s,uid}=await staff();const project_id=String(f.get('project_id'));const nums=['capex','opex_annual','revenue_annual','ebitda_annual','tax_rate','discount_rate','terminal_value','total_project_cost','sponsor_equity','banquisqueya_equity','third_party_equity','senior_debt','mezzanine','irr','npv','dscr','payback_years','revenue_growth','opex_growth','senior_debt_rate','senior_debt_term_years','debt_grace_years','depreciation_years','working_capital_pct_revenue','terminal_growth'];const p:any={project_id,updated_by:uid,status:String(f.get('status')||'draft'),currency:String(f.get('currency')||'USD'),base_year:Number(f.get('base_year'))||null,projection_years:Number(f.get('projection_years'))||10,assumptions:String(f.get('assumptions')||''),sensitivity_notes:String(f.get('sensitivity_notes')||'')};for(const n of nums)p[n]=f.get(n)===''||f.get(n)===null?null:Number(f.get(n));const{error}=await s.from('project_financial_models').upsert(p,{onConflict:'project_id'});if(error)throw new Error(error.message);revalidatePath('/admin/projects/'+project_id+'/financial')}
export async function saveScenario(f:FormData){const{s}=await staff();const project_id=String(f.get('project_id'));const{error}=await s.from('project_financial_scenarios').upsert({project_id,name:String(f.get('name')),scenario_type:String(f.get('scenario_type')),revenue_factor:Number(f.get('revenue_factor')||1),capex_factor:Number(f.get('capex_factor')||1),opex_factor:Number(f.get('opex_factor')||1),discount_rate:f.get('discount_rate')?Number(f.get('discount_rate')):null,irr:f.get('irr')?Number(f.get('irr')):null,npv:f.get('npv')?Number(f.get('npv')):null,dscr:f.get('dscr')?Number(f.get('dscr')):null,notes:String(f.get('notes')||'')},{onConflict:'project_id,scenario_type'});if(error)throw new Error(error.message);revalidatePath('/admin/projects/'+project_id+'/financial')}
