'use server'
import { revalidatePath } from 'next/cache'
import { redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'
import { isStaffRole } from '@/lib/auth/roles'
async function staff(){const s=await createClient();const{data:c}=await s.auth.getClaims();const uid=c?.claims?.sub as string|undefined;if(!uid)redirect('/login');const{data:p}=await s.from('profiles').select('role').eq('id',uid).maybeSingle();if(!isStaffRole(p?.role))redirect('/admin');return{s,uid}}
export async function initializeFinancial(f:FormData){const{s}=await staff();const project_id=String(f.get('project_id'));const application_id=f.get('application_id')||null;const{error}=await s.rpc('initialize_financial_structuring',{p_project_id:project_id,p_application_id:application_id});if(error)throw new Error(error.message);revalidatePath('/admin/projects/'+project_id+'/financial')}
export async function saveFinancialModel(f:FormData){const{s,uid}=await staff();const project_id=String(f.get('project_id'));const nums=['capex','opex_annual','revenue_annual','ebitda_annual','tax_rate','discount_rate','terminal_value','total_project_cost','sponsor_equity','banquisqueya_equity','third_party_equity','senior_debt','mezzanine','irr','npv','dscr','payback_years','revenue_growth','opex_growth','senior_debt_rate','senior_debt_term_years','debt_grace_years','depreciation_years','working_capital_pct_revenue','terminal_growth'];const p:any={project_id,updated_by:uid,status:String(f.get('status')||'draft'),currency:String(f.get('currency')||'USD'),base_year:Number(f.get('base_year'))||null,projection_years:Number(f.get('projection_years'))||10,assumptions:String(f.get('assumptions')||''),sensitivity_notes:String(f.get('sensitivity_notes')||'')};for(const n of nums)p[n]=f.get(n)===''||f.get(n)===null?null:Number(f.get(n));const{error}=await s.from('project_financial_models').upsert(p,{onConflict:'project_id'});if(error)throw new Error(error.message);revalidatePath('/admin/projects/'+project_id+'/financial')}
export async function saveScenario(f:FormData){const{s}=await staff();const project_id=String(f.get('project_id'));const{error}=await s.from('project_financial_scenarios').upsert({project_id,name:String(f.get('name')),scenario_type:String(f.get('scenario_type')),revenue_factor:Number(f.get('revenue_factor')||1),capex_factor:Number(f.get('capex_factor')||1),opex_factor:Number(f.get('opex_factor')||1),discount_rate:f.get('discount_rate')?Number(f.get('discount_rate')):null,irr:f.get('irr')?Number(f.get('irr')):null,npv:f.get('npv')?Number(f.get('npv')):null,dscr:f.get('dscr')?Number(f.get('dscr')):null,notes:String(f.get('notes')||'')},{onConflict:'project_id,scenario_type'});if(error)throw new Error(error.message);revalidatePath('/admin/projects/'+project_id+'/financial')}
