import Link from 'next/link'
import { redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'
import { signOut } from './actions'
import { isStaffRole, ROLE_LABELS } from '@/lib/auth/roles'
import BrandLogo from '@/components/BrandLogo'

export default async function InvestorDashboard() {
 const s=await createClient()
 const {data:{user}}=await s.auth.getUser()
 if(!user)redirect('/login')
 const [{data:profile},{data:investor},{data:investments},{data:transactions}]=await Promise.all([
  s.from('profiles').select('full_name,role').eq('id',user.id).maybeSingle(),
  s.from('investors').select('id,investor_type,status,kyc_status,country,risk_profile').eq('user_id',user.id).maybeSingle(),
  s.from('investments').select('id,principal,currency,status,invested_at,maturity_date,project_id').eq('investor_id',investor?.id||'').order('created_at',{ascending:false}).limit(10),
  s.from('transactions').select('id,type,amount,currency,status,transaction_date,description').order('transaction_date',{ascending:false}).limit(8)
 ])
 const totalByCurrency=(investments??[]).reduce((acc:any,item:any)=>{const c=item.currency||'USD';acc[c]=(acc[c]||0)+Number(item.principal||0);return acc},{})
 const totalInvested=Object.values(totalByCurrency).reduce((a:any,b:any)=>a+Number(b),0)
 const displayName=profile?.full_name||user.email||'Inversionista'
 const kycLabel=({pending:'Pendiente',in_review:'En revisión',approved:'Aprobado',rejected:'Rechazado'} as any)[investor?.kyc_status||'pending']||investor?.kyc_status
 return <div className="investor-portal">
  <header className="portal-topbar"><Link href="/"><BrandLogo compact/></Link><div className="topbar-right">{isStaffRole(profile?.role)&&<Link className="btn secondary" href="/admin">Administración · {ROLE_LABELS[profile!.role as keyof typeof ROLE_LABELS]}</Link>}<form action={signOut}><button className="btn secondary" type="submit">Cerrar sesión</button></form></div></header>
  <main className="dashboard"><div className="container dashboard-wide">
   <div className="dashboard-heading"><div><span className="eyebrow">BANQUISQUEYA & TRUST · INVESTOR PORTAL</span><h1>Buenos días, {displayName}</h1><p className="muted">Resumen de tu relación con el fondo, inversiones y documentación.</p></div><Link href="/investor/profile" className="btn primary">Mi perfil y KYC</Link></div>
   <div className="metric-grid investor-metrics"><div className="metric-card"><span className="metric-icon">◈</span><div><div className="metric-label">Capital invertido</div><div className="metric-value">{totalInvested.toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0})}</div><div className="metric-caption">{Object.keys(totalByCurrency).length||1} moneda(s) registrada(s)</div></div></div><div className="metric-card"><span className="metric-icon">✓</span><div><div className="metric-label">Estado KYC</div><div className="metric-value metric-text">{kycLabel}</div><div className="metric-caption">Documentación y cumplimiento</div></div></div><div className="metric-card"><span className="metric-icon">◎</span><div><div className="metric-label">Inversiones</div><div className="metric-value">{investments?.length||0}</div><div className="metric-caption">Posiciones registradas</div></div></div><div className="metric-card"><span className="metric-icon">↗</span><div><div className="metric-label">Cuenta</div><div className="metric-value metric-text">{investor?.status||'Pendiente'}</div><div className="metric-caption">{investor?.risk_profile||'Perfil por completar'}</div></div></div></div>
   {!investor&&<section className="notice-panel"><div><strong>Completa tu expediente de inversionista</strong><p>Necesitamos tu perfil, KYC y documentación para habilitar plenamente tu relación con BanQuisqueya & Trust.</p></div><Link href="/investor/profile" className="btn primary">Completar ahora</Link></section>}
   <div className="dashboard-columns"><section className="panel"><div className="panel-heading"><div><h2>Distribución de cartera</h2><p className="muted">Capital registrado por moneda.</p></div><Link href="/investor/investments" className="text-link">Ver inversiones →</Link></div>{Object.keys(totalByCurrency).length?<div className="allocation-list">{Object.entries(totalByCurrency).map(([currency,value]:any)=>{const pct=totalInvested?Number(value)/totalInvested*100:0;return <div className="allocation-row" key={currency}><div className="allocation-meta"><span>{currency}</span><strong>{Number(value).toLocaleString('en-US')}</strong></div><div className="pipeline-track"><span style={{width:pct+'%'}}/></div><small>{pct.toFixed(0)}% del capital registrado</small></div>})}</div>:<div className="empty-state">Aún no hay inversiones registradas. Tus nuevas posiciones aparecerán aquí.</div>}</section>
   <section className="panel"><div className="panel-heading"><div><h2>Estado de cuenta</h2><p className="muted">Acciones y documentación.</p></div></div><div className="action-grid"><Link href="/investor/applications" className="action-card"><strong>Mis solicitudes</strong><span>Seguimiento de financiamientos</span></Link><Link href="/investor/documents" className="action-card"><strong>Documentos</strong><span>Contratos y archivos</span></Link><Link href="/investor/profile" className="action-card"><strong>KYC</strong><span>Actualizar expediente</span></Link></div></section></div>
   <section className="panel"><div className="panel-heading"><div><h2>Mis inversiones</h2><p className="muted">Posiciones recientes y vencimientos.</p></div></div>{!investments?.length?<div className="empty-state">No hay inversiones registradas todavía.</div>:<div className="table-wrap"><table className="table professional-table"><thead><tr><th>Proyecto</th><th>Capital</th><th>Estado</th><th>Invertido</th><th>Vencimiento</th></tr></thead><tbody>{investments.map(x=><tr key={x.id}><td><strong>Proyecto {x.project_id||'—'}</strong></td><td>{x.currency} {Number(x.principal).toLocaleString('en-US')}</td><td><span className="status-chip">{x.status}</span></td><td>{x.invested_at?new Date(x.invested_at).toLocaleDateString('es-DO'):'—'}</td><td>{x.maturity_date?new Date(x.maturity_date).toLocaleDateString('es-DO'):'—'}</td></tr>)}</tbody></table></div>}</section>
   <section className="panel"><div className="panel-heading"><div><h2>Últimas transacciones</h2><p className="muted">Movimientos registrados en tu cuenta.</p></div></div>{!transactions?.length?<div className="empty-state">No hay transacciones registradas todavía.</div>:<div className="table-wrap"><table className="table professional-table"><thead><tr><th>Fecha</th><th>Tipo</th><th>Monto</th><th>Estado</th></tr></thead><tbody>{transactions.map(x=><tr key={x.id}><td>{new Date(x.transaction_date).toLocaleDateString('es-DO')}</td><td>{x.type}</td><td>{x.currency} {Number(x.amount).toLocaleString('en-US')}</td><td><span className="status-chip">{x.status}</span></td></tr>)}</tbody></table></div>}</section>
  </div></main>
 </div>
}