'use server'
import { revalidatePath } from 'next/cache'
import { redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'
import { isStaffRole } from '@/lib/auth/roles'
async function staff(){const s=await createClient();const{data:c}=await s.auth.getClaims();const uid=c?.claims?.sub as string|undefined;if(!uid)redirect('/login');const{data:p}=await s.from('profiles').select('role').eq('id',uid).maybeSingle();if(!isStaffRole(p?.role))redirect('/admin');return{s,uid}}
export async function initializeMandate(f:FormData){const{s}=await staff();const project_id=String(f.get('project_id'));const{data,error}=await s.rpc('initialize_capital_mandate',{p_project_id:project_id,p_capital_source_id:String(f.get('capital_source_id')),p_match_id:f.get('match_id')||null});if(error)throw new Error(error.message);revalidatePath('/admin/capital-mandates');if(data)redirect('/admin/capital-mandates/'+data)}
export async function updateMandate(f:FormData){const{s}=await staff();const id=String(f.get('id'));const{error}=await s.from('capital_mandates').update({status:String(f.get('status')),mandate_type:String(f.get('mandate_type')||'capital_introduction'),target_amount:Number(f.get('target_amount')||0),currency:String(f.get('currency')||'USD'),target_instrument:String(f.get('target_instrument')||''),mandate_scope:String(f.get('mandate_scope')||''),exclusivity:String(f.get('exclusivity')||''),fee_structure:String(f.get('fee_structure')||''),validity_until:f.get('validity_until')||null}).eq('id',id);if(error)throw new Error(error.message);revalidatePath('/admin/capital-mandates')}
export async function updateRoom(f:FormData){const{s}=await staff();const id=String(f.get('id'));const{error}=await s.from('capital_transaction_rooms').update({status:String(f.get('status')),confidentiality_notice:String(f.get('confidentiality_notice')||'')}).eq('id',id);if(error)throw new Error(error.message);revalidatePath('/admin/capital-mandates/'+String(f.get('mandate_id')))}
