import Link from 'next/link'
import { createClient } from '@/lib/supabase/server'
import { submitApplication } from '../actions'

export default async function NewApplication(){
 const s=await createClient()
 const {data:subsectors}=await s.from('sector_subtaxonomy').select('id,code,name,sector_id,sector_taxonomy(name)').eq('active',true).order('display_order')
 return <div className="dashboard"><div className="container"><Link href="/investor/applications">← Mis solicitudes</Link><h1 style={{marginTop:16}}>Presentar proyecto u oportunidad</h1><p className="muted">Indica cómo deseas trabajar con BanQuisqueya & Trust: financiamiento, Joint Venture, desarrollo, PPP o alianza estratégica.</p><form action={submitApplication} className="card" style={{display:'grid',gap:14,maxWidth:900}}>
 <h2>Empresa / promotor</h2><div className="grid"><label>Razón social<input name="legal_name" required /></label><label>Nombre de contacto<input name="contact_name" required /></label><label>Teléfono<input name="phone" /></label><label>País<input name="country" required /></label></div>
 <h2 style={{marginTop:10}}>Modelo de relación</h2><div className="grid"><label>Tipo de relación<select name="engagement_type"><option value="financing">Financiamiento</option><option value="joint_venture">Joint Venture</option><option value="project_development">Project Development</option><option value="strategic_partnership">Alianza estratégica</option><option value="ppp">PPP / Asociación Público-Privada</option><option value="debt_financing">Financiamiento de deuda</option><option value="equity_investment">Inversión de capital</option><option value="co_investment">Co-inversión</option><option value="acquisition_development">Adquisición y desarrollo</option><option value="refinancing">Refinanciamiento</option></select></label><label>Valor estimado del terreno / activo<input name="land_contribution_value" type="number" min="0" step="0.01" placeholder="Si aplica" /></label><label>Aporte del sponsor / cliente<input name="sponsor_contribution_value" type="number" min="0" step="0.01" placeholder="Valor estimado" /></label><label>Aporte de BanQuisqueya solicitado<input name="requested_equity" type="number" min="0" step="0.01" placeholder="Si aplica" /></label></div><label>Descripción del aporte del sponsor / cliente<textarea name="sponsor_contribution_description" rows={4} placeholder="Terreno, permisos, derechos, estudios, operación, know-how, etc." /></label>
 <h2 style={{marginTop:10}}>Clasificación de inversión</h2><p className="muted">Selecciona un sector y el subsector que mejor describa la oportunidad. Esta clasificación se utilizará para due diligence, comité y matching con fuentes de capital.</p><div className="grid"><label>Sector<select name="sector" required><option value="">Seleccionar sector</option><option value="Energy, Power & Utilities">Energy, Power & Utilities</option><option value="Renewable Energy & Energy Transition">Renewable Energy & Energy Transition</option><option value="Digital Infrastructure, Data Centers & Cloud">Digital Infrastructure, Data Centers & Cloud</option><option value="Telecommunications, Media & Connectivity">Telecommunications, Media & Connectivity</option><option value="Technology, AI, Software & Cybersecurity">Technology, AI, Software & Cybersecurity</option><option value="Healthcare, Life Sciences & Pharmaceuticals">Healthcare, Life Sciences & Pharmaceuticals</option><option value="Financial Services, Fintech & Payments">Financial Services, Fintech & Payments</option><option value="Infrastructure, Transportation & Logistics">Infrastructure, Transportation & Logistics</option><option value="Real Estate, Hospitality & Tourism">Real Estate, Hospitality & Tourism</option><option value="Industrials, Manufacturing & Advanced Industries">Industrials, Manufacturing & Advanced Industries</option><option value="Agribusiness, Food & Agriculture">Agribusiness, Food & Agriculture</option><option value="Mining, Metals & Critical Minerals">Mining, Metals & Critical Minerals</option><option value="Climate, Environmental Services & Circular Economy">Climate, Environmental Services & Circular Economy</option><option value="Defense, Aerospace & Security">Defense, Aerospace & Security</option><option value="Consumer, Retail & Consumer Services">Consumer, Retail & Consumer Services</option><option value="Education & Human Capital">Education & Human Capital</option><option value="Senior Living, Wellness & Quality-of-Life Services">Senior Living, Wellness & Quality-of-Life Services</option><option value="Bioeconomy & Biotechnology">Bioeconomy & Biotechnology</option><option value="Water, Wastewater & Water Infrastructure">Water, Wastewater & Water Infrastructure</option><option value="Social Infrastructure & Affordable Housing">Social Infrastructure & Affordable Housing</option></select></label><label>Subsector<select name="subsector_id" required><option value="">Seleccionar subsector</option>{(subsectors||[]).map((x:any)=><option key={x.id} value={x.id}>{x.sector_taxonomy?.name} — {x.name}</option>)}</select></label></div>
 <h2 style={{marginTop:10}}>Proyecto</h2><div className="grid"><label>Nombre del proyecto<input name="project_name" required /></label><label>Etapa del proyecto<input name="project_stage" placeholder="Desarrollo, construcción, operación..." /></label><label>Monto solicitado<input name="requested_amount" type="number" min="0" step="0.01" required /></label><label>Moneda<select name="currency"><option>USD</option><option>EUR</option><option>GBP</option><option>CAD</option><option>RD$</option></select></label></div><label>Descripción del proyecto<textarea name="project_description" rows={6} required /></label><label>Destino de los fondos<textarea name="funding_purpose" rows={4} placeholder="Construcción, CAPEX, adquisición, expansión..." /></label><label>Fuente de repago<textarea name="repayment_source" rows={4} /></label><button className="btn primary" type="submit">Enviar solicitud</button>
 </form></div></div>
}