import Link from 'next/link'
import {redirect} from 'next/navigation'
import {createClient} from '@/lib/supabase/server'
import InvestorNav from '@/components/InvestorNav'

const kyc:Record<string,string>={pending:'Pendiente',in_review:'En revisión',approved:'Aprobado',rejected:'Rechazado'}
const risk:Record<string,string>={conservative:'Conservador',moderate:'Moderado',aggressive:'Dinámico'}
const date=(v:string|null)=>v?new Date(v).toLocaleDateString('es-DO',{year:'numeric',month:'long',day:'2-digit'}):'—'

export default async function InvestorProfile(){
  const s=await createClient();const {data:{user}}=await s.auth.getUser();if(!user)redirect('/login')
  const {data:p}=await s.from('profiles').select('full_name,role').eq('id',user.id).maybeSingle()
  const {data:i}=await s.from('investors').select('investor_type,status,kyc_status,country,nationality,address,city,state_province,postal_code,document_type,source_of_funds,beneficial_owner_name,beneficial_owner_relationship,kyc_submitted_at,risk_profile').eq('user_id',user.id).maybeSingle()
  const {data:reviews}=i?await s.from('kyc_reviews').select('decision,notes,created_at').eq('investor_id',i.id).order('created_at',{ascending:false}).limit(5)):{data:[] as any[]}
  return <div className="investor-portal"><header className="portal-topbar"><Link href="/investor" className="investor-topbar-brand"><span className="brand-logo"><img className="brand-mark" src="/banquisqueya-original-mark.webp" alt="BanQuisqueya & Trust"/><span className="brand-wordmark"><strong>BANQUISQUEYA</strong><span className="brand-subline"><i/> &amp; TRUST</span></span></span></Link><div className="topbar-right"><Link className="btn secondary" href="/investor">Dashboard</Link></div></header>
  <main className="dashboard"><div className="container dashboard-wide"><InvestorNav active="KYC / Compliance"/>
    <section className="dashboard-heading"><div><span className="eyebrow">INVESTOR PROFILE · KYC &amp; COMPLIANCE</span><h1>Expediente institucional</h1><p className="muted">Identidad, perfil de riesgo y estado de cumplimiento de la relación.</p></div></section>
    <div className="metric-grid"><div className="metric-card"><div><div className="metric-label">Estado KYC</div><div className="metric-value metric-text">{kyc[i?.kyc_status||'pending']||i?.kyc_status||'Pendiente'}</div><div className="metric-caption">Expediente de cumplimiento</div></div></div><div className="metric-card"><div><div className="metric-label">Perfil de riesgo</div><div className="metric-value metric-text">{risk[i?.risk_profile||'']||i?.risk_profile||'No definido'}</div><div className="metric-caption">Clasificación registrada</div></div></div><div className="metric-card"><div><div className="metric-label">Estado de relación</div><div className="metric-value metric-text">{i?.status||'Pendiente'}</div><div className="metric-caption">Cuenta institucional</div></div></div><div className="metric-card"><div><div className="metric-label">KYC enviado</div><div className="metric-value metric-text">{date(i?.kyc_submitted_at||null)}</div><div className="metric-caption">{i?.investor_type||'individual'}</div></div></div></div>
    <div className="dashboard-columns"><section className="panel"><div className="panel-heading"><div><span className="eyebrow">IDENTIFICATION</span><h2>Datos del expediente</h2></div></div><div className="profile-detail-grid">
      <div><span>Nombre</span><strong>{p?.full_name||user.email||'—'}</strong></div><div><span>País</span><strong>{i?.country||'—'}</strong></div><div><span>Nacionalidad</span><strong>{i?.nationality||'—'}</strong></div><div><span>Dirección</span><strong>{i?.address||'—'}</strong></div><div><span>Ciudad / Estado</span><strong>{[i?.city,i?.state_province].filter(Boolean).join(' · ')||'—'}</strong></div><div><span>Código postal</span><strong>{i?.postal_code||'—'}</strong></div><div><span>Documento</span><strong>{i?.document_type||'—'}</strong></div><div><span>Origen de fondos</span><strong>{i?.source_of_funds||'—'}</strong></div><div><span>Beneficiario final</span><strong>{i?.beneficial_owner_name||'—'}</strong></div><div><span>Relación</span><strong>{i?.beneficial_owner_relationship||'—'}</strong></div>
    </div></section><section className="panel"><div className="panel-heading"><div><span className="eyebrow">REVIEW TRAIL</span><h2>Historial KYC</h2></div></div>{!reviews?.length?<div className="empty-state">Todavía no hay revisiones registradas.</div>:(reviews||[]).map(r=><div className="review-row" key={r.created_at}><div><strong>{kyc[r.decision]||r.decision||'Revisión'}</strong><p>{r.notes||'Sin observaciones registradas.'}</p></div><small>{date(r.created_at)}</small></div>)}</section></div>
    <section className="notice-panel"><div><strong>Próximo paso</strong><p>La edición de datos, carga documental y workflow de revisión se habilitarán desde este expediente a medida que completemos el módulo KYC.</p></div><Link href="/investor/documents" className="btn primary">Ver documentos</Link></section>
  </div></main></div>
}
