'use server'
import { revalidatePath } from 'next/cache'
import { redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'
import { isStaffRole } from '@/lib/auth/roles'
async function staff(){const s=await createClient();const{data:c}=await s.auth.getClaims();const uid=c?.claims?.sub as string|undefined;if(!uid)redirect('/login');const{data:p}=await s.from('profiles').select('role').eq('id',uid).maybeSingle();if(!isStaffRole(p?.role))redirect('/admin');return{s,uid,role:p.role}}
export async function initializeLegal(f:FormData){const{s}=await staff();const project_id=String(f.get('project_id'));const application_id=f.get('application_id')||null;const{error}=await s.rpc('initialize_legal_contracting',{p_project_id:project_id,p_application_id:application_id});if(error)throw new Error(error.message);revalidatePath('/admin/projects/'+project_id+'/legal')}
export async function updateCondition(f:FormData){const{s,uid,role}=await staff();const id=String(f.get('id'));const status=String(f.get('status'));if(['satisfied','waived'].includes(status)&&!['admin','legal','contract_manager','executive','compliance','finance','due_diligence','risk_manager'].includes(role))throw new Error('Rol no autorizado para cerrar esta condición.');const{error}=await s.from('project_legal_conditions').update({status,owner_role:String(f.get('owner_role')||''),due_date:f.get('due_date')||null,notes:String(f.get('notes')||''),satisfied_by:['satisfied','waived'].includes(status)?uid:null,satisfied_at:['satisfied','waived'].includes(status)?new Date().toISOString():null}).eq('id',id);if(error)throw new Error(error.message);revalidatePath('/admin/projects/'+String(f.get('project_id'))+'/legal')}
export async function updateContractItem(f:FormData){const{s,role}=await staff();if(!['admin','legal','contract_manager','executive'].includes(role))throw new Error('Solo Legal/Contracts/Executive/Admin puede actualizar documentos contractuales.');const id=String(f.get('id'));const{error}=await s.from('project_contracting_checklists').update({status:String(f.get('status')),legal_workflow_id:f.get('legal_workflow_id')||null,notes:String(f.get('notes')||'')}).eq('id',id);if(error)throw new Error(error.message);revalidatePath('/admin/projects/'+String(f.get('project_id'))+'/legal')}
